const Answers = [
    {
      'id': '1',
      'UID': '1',
      'questionID': 130,
      'answer': 'My favorite holiday is Christmas because of the festive atmosphere and time spent with family.',
    },
    {
      'id': '2',
      'UID': '2',
      'questionID': 130,
      'answer': 'My favorite holiday is Halloween because I love dressing up in costumes and the spooky decorations.',
    },
    {
      'id': '3',
      'UID': '3',
      'questionID': 130,
      'answer': 'My favorite holiday is Thanksgiving because of the delicious food and quality time with loved ones.',
    },
    {
      'id': '4',
      'UID': '4',
      'questionID': 130,
      'answer': "My favorite holiday is New Year's Eve because it's a time for new beginnings and celebrating with friends.",
    },
    {
      'id': '5',
      'UID': '5',
      'questionID': 130,
      'answer': "My favorite holiday is Valentine's Day because of the opportunity to show love and appreciation to those closest to me.",
    },
    {
      'id': '6',
      'UID': '6',
      'questionID': 130,
      'answer': 'My favorite holiday is Easter because of the beautiful spring weather and spending time with family.',
    },
    {
      'id': '7',
      'UID': '7',
      'questionID': 130,
      'answer': "My favorite holiday is Independence Day because of the fireworks, barbecues, and celebration of our country's history.",
    },
    {
      'id': '8',
      'UID': '8',
      'questionID': 130,
      'answer': 'My favorite holiday is Hanukkah because of the warmth and light it brings to the winter season.',
    },
    {
      'id': '9',
      'UID': '9',
      'questionID': 130,
      'answer': 'My favorite holiday is Diwali because of the vibrant colors, delicious food, and celebration of light over darkness.',
    },
    {
      'id': '10',
      'UID': '10',
      'questionID': 130,
      'answer': "My favorite holiday is St. Patrick's Day because of the fun and festive atmosphere and excuse to wear green.",
    },
    {
      'id': '11',
      'UID': '11',
      'questionID': 130,
      'answer': 'My favorite holiday is Labor Day because of the chance to relax and enjoy the last days of summer before the fall season begins.',
    },
    {
      'id': '12',
      'UID': '12',
      'questionID': 130,
      'answer': 'My favorite holiday is Memorial Day because of the opportunity to honor and remember those who have served our country.',
    },
    {
      'id': '13',
      'UID': '13',
      'questionID': 130,
      'answer': 'My favorite holiday is Earth Day because of the focus on sustainability and protecting our planet for future generations.',
    },
    {
      'id': '14',
      'UID': '14',
      'questionID': 130,
      'answer': 'My favorite holiday is Mardi Gras because of the colorful parades, delicious food, and lively music.',
    },
    {
      'id': '15',
      'UID': '15',
      'questionID': 130,
      'answer': 'My favorite holiday is Christmas Eve because of the anticipation and excitement leading up to Christmas Day.',
    },
    {
      'id': '16',
      'UID': '16',
      'questionID': 130,
      'answer': 'My favorite holiday is Rosh Hashanah because of the reflection and renewal it brings to the new year.',
    },
    {
      'id': '17',
      'UID': '17',
      'questionID': 130,
      'answer': 'My favorite holiday is Kwanzaa because of the emphasis on community, culture, and tradition.',
    },
    {
      'id': '18',
      'UID': '18',
      'questionID': 130,
      'answer': 'My favorite holiday is Ramadan because of the focus on spirituality, self-reflection, and charity.',
    },
    {
      'id': '19',
      'UID': '19',
      'questionID': 130,
      'answer': 'My favorite holiday is Cinco de Mayo because of the delicious food, lively music, and celebration of Mexican culture.',
    },
    {
      'id': '20',
      'UID': '20',
      'questionID': 130,
      'answer': 'My favorite holiday is Bastille Day because of the celebration of French history and culture.',
    },
    {
      'id': '21',
      'UID': '21',
      'questionID': 130,
      'answer': 'My favorite holiday is Chinese New Year because of the festive atmosphere and the red envelopes.',
    },
];
export default Answers;
