const TodaysLeaders = {
  question: 'This is the maximum amount of charcters to ask in a question',
  date: '2023-02-20',
  answers: [
    {
      'id': 1,
      'pic': require('../../../assets/DummyData/m1.jpg'),
      'firstName': 'Noah',
      'lastName': 'Patel',
      'city': 'San Jose',
      'state': 'CA',
      'country': 'USA',
      'gender': 'Male',
      'birthday': '6/27/02',
      'age': 22,
      'maritalStatus': 'Single',
      'education': 'High School Graduate',
      'favAnimal': 'badger',
      'favFood': 'banana split',
      'charity': 'American Lung Association',
      'question': 'My favorite vegetable is…',
      'answer': 'brocilli. I like the taste',
      'votes': 336,
    },
    {
      'id': 2,
      'pic': require('../../../assets/DummyData/m2.jpg'),
      'firstName': 'Oliver',
      'lastName': 'Johnson',
      'city': 'Phoenix',
      'state': 'AR',
      'country': 'USA',
      'gender': 'Male',
      'birthday': '1/2/05',
      'age': 17,
      'maritalStatus': 'Partnered',
      'education': 'Some College',
      'favAnimal': 'kangaroo',
      'favFood': 'fish and chips',
      'charity': 'Best Friends Animal Society',
      'question': 'My favorite vegetable is…',
      'answer': 'french green beans. Seems to be put in a lot of casssroles',
      'votes': 138,
    },
    {
      'id': 3,
      'pic': require('../../../assets/DummyData/m3.jpg'),
      'firstName': 'William',
      'lastName': 'Jones',
      'city': 'Seattle',
      'state': 'WA',
      'country': 'USA',
      'gender': 'Male',
      'birthday': '7/17/98',
      'age': 24,
      'maritalStatus': 'Married',
      'education': 'College Graduate',
      'favAnimal': 'elephant',
      'favFood': 'mexican food',
      'charity': 'National UrbanLeaugue',
      'question': 'My favorite vegetable is…',
      'answer': 'carrots because I like the way they are mushed when cooked',
      'votes': 487,
    },
    {
      'id': 4,
      'pic': require('../../../assets/DummyData/m4.jpg'),
      'firstName': 'James',
      'lastName': 'Lee',
      'city': 'Concord',
      'state': 'NH',
      'country': 'USA',
      'gender': 'Male',
      'birthday': '5/2/02',
      'age': 20,
      'maritalStatus': 'Single',
      'education': 'Some College',
      'favAnimal': 'ant',
      'favFood': 'duck',
      'charity': 'Partnership to End Addiction',
      'question': 'My favorite vegetable is…',
      'answer': 'corn, I like it on the cob',
      'votes': 221,
    },
    {
      'id': 5,
      'pic': require('../../../assets/DummyData/m5.jpg'),
      'firstName': 'Jose',
      'lastName': 'Martinez',
      'city': 'South San Francisco',
      'state': 'CA',
      'country': 'USA',
      'gender': 'Male',
      'birthday': '5/31/01',
      'age': 21,
      'maritalStatus': 'Single',
      'education': 'College Graduate',
      'favAnimal': 'bear',
      'favFood': 'sweet potatoes',
      'charity': 'The Hungar Project',
      'question': 'My favorite vegetable is…',
      'answer': "bell pepper. It's fun to dip",
      'votes': 766,
    },
    {
      'id': 6,
      'pic': require('../../../assets/DummyData/m6.jpg'),
      'firstName': 'Steve',
      'lastName': 'Rameriz',
      'city': 'Jacksonville',
      'state': 'FL',
      'country': 'USA',
      'gender': 'Male',
      'birthday': '11/22/00',
      'age': 21,
      'maritalStatus': 'Partnered',
      'education': 'Some College',
      'favAnimal': 'dog',
      'favFood': 'ribs',
      'charity': 'American Lung Association',
      'question': 'My favorite vegetable is…',
      'answer': 'celery - ants on a log',
      'votes': 443,
    },
    {
      'id': 7,
      'pic': require('../../../assets/DummyData/m7.jpg'),
      'firstName': 'Christopher',
      'lastName': 'Jackson',
      'city': 'Charlotte',
      'state': 'NC',
      'country': 'USA',
      'gender': 'Male',
      'birthday': '5/25/79',
      'age': 43,
      'maritalStatus': 'Single',
      'education': 'Some College',
      'favAnimal': 'cat',
      'favFood': 'fish tacos',
      'charity': 'Best Friends Animal Society',
      'question': 'My favorite vegetable is…',
      'answer': 'cucumbers for health benefits',
      'votes': 356,
    },
    {
      'id': 8,
      'pic': require('../../../assets/DummyData/m8.jpg'),
      'firstName': 'Matthew',
      'lastName': 'Martin',
      'city': 'Denver',
      'state': 'CO',
      'country': 'USA',
      'gender': 'Male',
      'birthday': '2/10/95',
      'age': 27,
      'maritalStatus': 'Single',
      'education': 'Some College',
      'favAnimal': 'fish',
      'favFood': 'chili dogs',
      'charity': 'National UrbanLeaugue',
      'question': 'My favorite vegetable is…',
      'answer': 'tomatoes - taste good',
      'votes': 752,
    },
    {
      'id': 9,
      'pic': require('../../../assets/DummyData/m9.jpg'),
      'firstName': 'Jason',
      'lastName': 'Coleman',
      'city': 'San Francisco',
      'state': 'CA',
      'country': 'USA',
      'gender': 'Male',
      'birthday': '6/14/88',
      'age': 33,
      'maritalStatus': 'Partnered',
      'education': 'Some College',
      'favAnimal': 'artic wolf',
      'favFood': 'avacado',
      'charity': 'Partnership to End Addiction',
      'question': 'My favorite vegetable is…',
      'answer': 'onions - Like the crunch',
      'votes': 137,
    },
    {
      'id': 10,
      'pic': '',
      'firstName': 'Alex',
      'lastName': 'Thompson',
      'city': 'Grand Rapids',
      'state': 'MI',
      'country': 'USA',
      'gender': 'Non-binary',
      'birthday': '9/24/05',
      'age': 16,
      'maritalStatus': 'Single',
      'education': 'Some College',
      'favAnimal': 'bullfrog',
      'favFood': 'empanada',
      'charity': 'The Hungar Project',
      'question': 'My favorite vegetable is…',
      'answer': 'Asparagus- so good',
      'votes': 117,
    },
    {
      'id': 11,
      'pic': require('../../../assets/DummyData/m10.jpg'),
      'firstName': 'Andrew',
      'lastName': 'Clark',
      'city': 'Tucson',
      'state': 'AZ',
      'country': 'USA',
      'gender': 'Male',
      'birthday': '8/17/03',
      'age': 19,
      'maritalStatus': 'Single',
      'education': 'High School Graduate',
      'favAnimal': 'shark',
      'favFood': 'cake',
      'charity': 'American Lung Association',
      'question': 'My favorite vegetable is…',
      'answer': 'peas - they roll',
      'votes': 132,
    },
    {
      'id': 12,
      'pic': require('../../../assets/DummyData/m11.jpg'),
      'firstName': 'Michael',
      'lastName': 'Ramirez',
      'city': 'Sacramento',
      'state': 'CA',
      'country': 'USA',
      'gender': 'Male',
      'birthday': '7/4/85',
      'age': 36,
      'maritalStatus': 'Divorced',
      'education': 'High School Graduate',
      'favAnimal': 'eagle',
      'favFood': 'shrimp',
      'charity': 'Best Friends Animal Society',
      'question': 'My favorite vegetable is…',
      'answer': 'jalapeño- spicy',
      'votes': 8,
    },
    {
      'id': 13,
      'pic': require('../../../assets/DummyData/m12.jpg'),
      'firstName': 'Joseph',
      'lastName': 'Lewis',
      'city': 'Atlanta',
      'state': 'GA',
      'country': 'USA',
      'gender': 'Male',
      'birthday': '4/1/72',
      'age': 50,
      'maritalStatus': 'prefer not to answer',
      'education': 'PhD',
      'favAnimal': 'flamingo',
      'favFood': 'doritos',
      'charity': 'National UrbanLeaugue',
      'question': 'My favorite vegetable is…',
      'answer': 'kale - health benefits',
      'votes': 100,
    },
    {
      'id': 14,
      'pic': require('../../../assets/DummyData/m13.jpg'),
      'firstName': 'Brandon',
      'lastName': 'Allen',
      'city': 'Omaha',
      'state': 'NE',
      'country': 'USA',
      'gender': 'Male',
      'birthday': '9/6/87',
      'age': 35,
      'maritalStatus': 'Partnered',
      'education': 'High School Graduate',
      'favAnimal': 'baboon',
      'favFood': 'hamburger',
      'charity': 'Partnership to End Addiction',
      'question': 'My favorite vegetable is…',
      'answer': 'spinach - good',
      'votes': 12,
    },
    {
      'id': 15,
      'pic': require('../../../assets/DummyData/m14.jpg'),
      'firstName': 'David',
      'lastName': 'Jerome',
      'city': 'Oakland',
      'state': 'CA',
      'country': 'USA',
      'gender': 'Male',
      'birthday': '2/22/96',
      'age': 26,
      'maritalStatus': 'Married',
      'education': 'College Graduate',
      'favAnimal': 'hummingbird',
      'favFood': 'chocolate chip cookies',
      'charity': 'The Hungar Project',
      'question': 'My favorite vegetable is…',
      'answer': 'potatoes- so many options',
      'votes': 474,
    },
    {
      'id': 16,
      'pic': require('../../../assets/DummyData/m15.jpg'),
      'firstName': 'James',
      'lastName': 'Green',
      'city': 'Miami',
      'state': 'FL',
      'country': 'USA',
      'gender': 'Male',
      'birthday': '2/22/05',
      'age': 17,
      'maritalStatus': 'Single',
      'education': 'Some High School',
      'favAnimal': 'fox',
      'favFood': 'lychees',
      'charity': 'American Lung Association',
      'question': 'My favorite vegetable is…',
      'answer': 'garlic - flavor',
      'votes': 58,
    },
    {
      'id': 17,
      'pic': require('../../../assets/DummyData/f1.jpg'),
      'firstName': 'Amy',
      'lastName': 'Rogers',
      'city': 'Rapid City',
      'state': 'IA',
      'country': 'USA',
      'gender': 'Female',
      'birthday': '3/17/89',
      'age': 35,
      'maritalStatus': 'Divorced',
      'education': 'Masters Degree',
      'favAnimal': 'caterpillar',
      'favFood': 'peanut butter and jelly',
      'charity': 'Best Friends Animal Society',
      'question': 'My favorite vegetable is…',
      'answer': 'cauliflower- crunch',
      'votes': 304,
    },
    {
      'id': 18,
      'pic': '',
      'firstName': 'Ashley',
      'lastName': 'Campbell',
      'city': 'Cleveland',
      'state': 'OH',
      'country': 'USA',
      'gender': 'Prefer not to answer',
      'birthday': '2/16/93',
      'age': 29,
      'maritalStatus': 'Divorced',
      'education': 'College Graduate',
      'favAnimal': 'chinchilla',
      'favFood': 'pierogies',
      'charity': 'National UrbanLeaugue',
      'question': 'My favorite vegetable is…',
      'answer': "squash - it's good",
      'votes': 105,
    },
    {
      'id': 19,
      'pic': require('../../../assets/DummyData/f2.jpg'),
      'firstName': 'Cedric',
      'lastName': 'Nelson',
      'city': 'Cincinnati',
      'state': 'OH',
      'country': 'USA',
      'gender': '-',
      'birthday': '6/2/96',
      'age': 26,
      'maritalStatus': 'Single',
      'education': 'High School Graduate',
      'favAnimal': 'barn owl',
      'favFood': 'french fries',
      'charity': 'Partnership to End Addiction',
      'question': 'My favorite vegetable is…',
      'answer': 'jalapeño- spicy and can handle',
      'votes': 978,
    },
    {
      'id': 20,
      'pic': require('../../../assets/DummyData/f3.jpg'),
      'firstName': 'Brittany',
      'lastName': 'Carter',
      'city': 'St. Louis',
      'state': 'MS',
      'country': 'USA',
      'gender': 'Female',
      'birthday': '4/22/03',
      'age': 19,
      'maritalStatus': 'Married',
      'education': 'Some High School',
      'favAnimal': 'donkey',
      'favFood': 'hot dogs',
      'charity': 'The Hungar Project',
      'question': 'My favorite vegetable is…',
      'answer': 'I like onions and the crunch. Many people do not know there are is so many different types',
      'votes': 964,
    },
    {
      'id': 21,
      'pic': require('../../../assets/DummyData/f4.jpg'),
      'firstName': 'Michele',
      'lastName': 'Riley',
      'city': 'Anchorage',
      'state': 'AK',
      'country': 'USA',
      'gender': 'Female',
      'birthday': '5/11/93',
      'age': 29,
      'maritalStatus': 'Married',
      'education': 'Masters Degree',
      'favAnimal': 'border collie',
      'favFood': 'brownies',
      'charity': 'American Lung Association',
      'question': 'My favorite vegetable is…',
      'answer': 'brocilli. I like the taste',
      'votes': 888,
    },
    {
      'id': 22,
      'pic': require('../../../assets/DummyData/f5.jpg'),
      'firstName': 'Sarah',
      'lastName': 'Evans',
      'city': 'Newport',
      'state': 'ME',
      'country': 'USA',
      'gender': 'Female',
      'birthday': '10/21/92',
      'age': 29,
      'maritalStatus': 'Single',
      'education': 'High School Graduate',
      'favAnimal': 'fly',
      'favFood': 'tacos',
      'charity': 'Best Friends Animal Society',
      'question': 'My favorite vegetable is…',
      'answer': 'french green beans. Seems to be put in a lot of casssroles',
      'votes': 968,
    },
    {
      'id': 23,
      'pic': require('../../../assets/DummyData/f6.jpg'),
      'firstName': 'Jenifer',
      'lastName': 'Turner',
      'city': 'Richmond',
      'state': 'VA',
      'country': 'USA',
      'gender': 'Female',
      'birthday': '11/1/90',
      'age': 31,
      'maritalStatus': 'Single',
      'education': 'Some College',
      'favAnimal': 'squirrel',
      'favFood': 'bagels',
      'charity': 'National UrbanLeaugue',
      'question': 'My favorite vegetable is…',
      'answer': 'carrots because I like the way they are mushed when cooked',
      'votes': 929,
    },
    {
      'id': 24,
      'pic': require('../../../assets/DummyData/f7.jpg'),
      'firstName': 'Lauren',
      'lastName': 'Cruz',
      'city': 'Raleigh',
      'state': 'NC',
      'country': 'USA',
      'gender': 'Female',
      'birthday': '12/9/95',
      'age': 26,
      'maritalStatus': 'Single',
      'education': 'Some College',
      'favAnimal': 'chipmunk',
      'favFood': 'scallops',
      'charity': 'Partnership to End Addiction',
      'question': 'My favorite vegetable is…',
      'answer': 'corn, I like it on the cob',
      'votes': 528,
    },
    {
      'id': 25,
      'pic': '',
      'firstName': 'Liz',
      'lastName': 'Parker',
      'city': 'Reno',
      'state': 'NV',
      'country': 'USA',
      'gender': 'Transgender',
      'birthday': '11/10/87',
      'age': 34,
      'maritalStatus': 'Widowed',
      'education': 'Some College',
      'favAnimal': 'penguin',
      'favFood': 'chicken nuggets',
      'charity': 'The Hungar Project',
      'question': 'My favorite vegetable is…',
      'answer': "bell pepper. It's fun to dip",
      'votes': 776,
    },
    {
      'id': 26,
      'pic': require('../../../assets/DummyData/f8.jpg'),
      'firstName': 'Emily',
      'lastName': 'Chen',
      'city': 'Portland',
      'state': 'OR',
      'country': 'USA',
      'gender': 'Female',
      'birthday': '6/18/01',
      'age': 21,
      'maritalStatus': 'Single',
      'education': 'College Graduate',
      'favAnimal': 'french bulldog',
      'favFood': 'figs',
      'charity': 'American Lung Association',
      'question': 'My favorite vegetable is…',
      'answer': 'celery - ants on a log',
      'votes': 249,
    },
    {
      'id': 27,
      'pic': require('../../../assets/DummyData/f9.jpg'),
      'firstName': 'Nicole',
      'lastName': 'Ng',
      'city': 'Madison',
      'state': 'WI',
      'country': 'USA',
      'gender': 'Female',
      'birthday': '5/14/00',
      'age': 22,
      'maritalStatus': 'Partnered',
      'education': 'Some College',
      'favAnimal': 'lizard',
      'favFood': 'bok choy',
      'charity': 'Best Friends Animal Society',
      'question': 'My favorite vegetable is…',
      'answer': 'cucumbers for health benefits',
      'votes': 579,
    },
    {
      'id': 28,
      'pic': require('../../../assets/DummyData/f10.jpg'),
      'firstName': 'Kayla',
      'lastName': 'Edwards',
      'city': 'Topeka',
      'state': 'KS',
      'country': 'USA',
      'gender': 'Female',
      'birthday': '11/25/90',
      'age': 31,
      'maritalStatus': 'Single',
      'education': 'College Graduate',
      'favAnimal': 'camel',
      'favFood': 'apple pie',
      'charity': 'National UrbanLeaugue',
      'question': 'My favorite vegetable is…',
      'answer': 'tomatoes - taste good',
      'votes': 870,
    },
    {
      'id': 29,
      'pic': require('../../../assets/DummyData/f11.jpg'),
      'firstName': 'Megan',
      'lastName': 'Cook',
      'city': 'Buffalo',
      'state': 'NY',
      'country': 'USA',
      'gender': 'Female',
      'birthday': '6/13/87',
      'age': 35,
      'maritalStatus': 'prefer not to answer',
      'education': 'Some College',
      'favAnimal': 'barracuda',
      'favFood': 'fast food',
      'charity': 'Partnership to End Addiction',
      'question': 'My favorite vegetable is…',
      'answer': 'onions - Like the crunch',
      'votes': 152,
    },
    {
      'id': 30,
      'pic': require('../../../assets/DummyData/f12.jpg'),
      'firstName': 'Tiffany',
      'lastName': 'Grahm',
      'city': 'Irvine',
      'state': 'CA',
      'country': 'USA',
      'gender': 'Female',
      'birthday': '8/27/99',
      'age': 23,
      'maritalStatus': 'Partnered',
      'education': 'Some College',
      'favAnimal': 'leopard',
      'favFood': 'chicken wrap',
      'charity': 'The Hungar Project',
      'question': 'My favorite vegetable is…',
      'answer': 'Asparagus- so good',
      'votes': 483,
    },
    {
      'id': 31,
      'pic': require('../../../assets/DummyData/f13.jpg'),
      'firstName': 'Heather',
      'lastName': 'Morgan',
      'city': 'Boise',
      'state': 'ID',
      'country': 'USA',
      'gender': 'Female',
      'birthday': '9/11/99',
      'age': 23,
      'maritalStatus': 'Single',
      'education': 'College Graduate',
      'favAnimal': 'butterfly',
      'favFood': 'lobster roll',
      'charity': 'American Lung Association',
      'question': 'My favorite vegetable is…',
      'answer': 'peas - they roll',
      'votes': 643,
    },
    {
      'id': 32,
      'pic': require('../../../assets/DummyData/f14.jpg'),
      'firstName': 'Jasmine',
      'lastName': 'Kim',
      'city': 'Birmingham',
      'state': 'AL',
      'country': 'USA',
      'gender': 'Female',
      'birthday': '8/6/03',
      'age': 19,
      'maritalStatus': 'Married',
      'education': 'Some College',
      'favAnimal': 'beagle',
      'favFood': 'bbq chicken',
      'charity': 'Best Friends Animal Society',
      'question': 'My favorite vegetable is…',
      'answer': 'jalapeño- spicy',
      'votes': 142,
    },
    {
      'id': 33,
      'pic': require('../../../assets/DummyData/f15.jpg'),
      'firstName': 'Chris',
      'lastName': 'Bailey',
      'city': 'Huntsville',
      'state': 'AL',
      'country': 'USA',
      'gender': 'Female',
      'birthday': '4/26/97',
      'age': 25,
      'maritalStatus': 'Single',
      'education': 'College Graduate',
      'favAnimal': 'antelope',
      'favFood': 'rice',
      'charity': 'National UrbanLeaugue',
      'question': 'My favorite vegetable is…',
      'answer': 'kale - health benefits',
      'votes': 135,
    },
    {
      'id': 34,
      'pic': require('../../../assets/DummyData/f16.jpg'),
      'firstName': 'Virginia',
      'lastName': 'Coolidge',
      'city': 'Santa Fe',
      'state': 'NM',
      'country': 'USA',
      'gender': 'Female',
      'birthday': '10/12/87',
      'age': 34,
      'maritalStatus': 'Single',
      'education': 'Masters Degree',
      'favAnimal': 'honey bee',
      'favFood': 'potato salad',
      'charity': 'Partnership to End Addiction',
      'question': 'My favorite vegetable is…',
      'answer': 'spinach - good',
      'votes': 458,
    },
    {
      'id': 35,
      'pic': '',
      'firstName': 'Joey',
      'lastName': 'Gaye',
      'city': 'Stanton',
      'state': 'MI',
      'country': 'USA',
      'gender': 'Non-binary',
      'birthday': '8/15/70',
      'age': 52,
      'maritalStatus': 'Partnered',
      'education': 'Some College',
      'favAnimal': 'panda',
      'favFood': 'eggs',
      'charity': 'The Hungar Project',
      'question': 'My favorite vegetable is…',
      'answer': 'potatoes- so many options',
      'votes': 868,
    },
  ],
};
export default TodaysLeaders;
