const TodaysLeaders = {
  question: 'One of my favorite days of my life was the day I...',
  date: '2023-02-23',
  answers: [
    {
      'id': 1,
      'pic': '',
      'firstName': 'Noah',
      'lastName': 'P',
      'city': 'San Jose',
      'gender': '--',
      'age': 22,
      'maritalStatus': 'Single',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'I adopted Luna, my furry friend',
      'votes': 700,
      'LEN': 31,
      'state': 'CA',
      'country': 'USA',
      'birthday': '6/27/02',
      'education': 'High School Graduate',
      'favAnimal': 'badger',
      'favFood': 'banana split',
      'charity': 'American Lung Association',
    },
    {
      'id': 2,
      'pic': require('../../../assets/DummyData/m1.jpg'),
      'firstName': 'Jose',
      'lastName': 'M',
      'city': 'South San Francisco',
      'gender': 'Male',
      'age': 21,
      'maritalStatus': '--',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'moved into my first apartment, filled with excitement and ideas how to decorate each room',
      'votes': 950,
      'LEN': 89,
      'state': 'CA',
      'country': 'USA',
      'birthday': '5/31/01',
      'education': 'College Graduate',
      'favAnimal': 'bear',
      'favFood': 'sweet potatoes',
      'charity': 'The Hungar Project',
    },
    {
      'id': 3,
      'pic': require('../../../assets/DummyData/m2.jpg'),
      'firstName': 'Oliver',
      'lastName': 'J',
      'city': 'Phoenix',
      'gender': 'Male',
      'age': 17,
      'maritalStatus': 'Partnered',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'visited the Eiffel Tower and captured its beauty.',
      'votes': 617,
      'LEN': 49,
      'state': 'AR',
      'country': 'USA',
      'birthday': '1/2/05',
      'education': 'Some College',
      'favAnimal': 'kangaroo',
      'favFood': 'fish and chips',
      'charity': 'Best Friends Animal Society',
    },
    {
      'id': 4,
      'pic': '',
      'firstName': 'William',
      'lastName': 'J',
      'city': 'Seattle',
      'gender': '--',
      'age': 24,
      'maritalStatus': 'Married',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'won the speech competition and felt like a superstar.',
      'votes': 192,
      'LEN': 53,
      'state': 'WA',
      'country': 'USA',
      'birthday': '7/17/98',
      'education': 'College Graduate',
      'favAnimal': 'elephant',
      'favFood': 'mexican food',
      'charity': 'National UrbanLeaugue',
    },
    {
      'id': 5,
      'pic': require('../../../assets/DummyData/m3.jpg'),
      'firstName': 'James',
      'lastName': 'L',
      'city': 'Concord',
      'gender': 'Male',
      'age': 20,
      'maritalStatus': 'Single',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': "got my driver's license, finally feeling free.",
      'votes': 421,
      'LEN': 46,
      'state': 'NH',
      'country': 'USA',
      'birthday': '5/2/02',
      'education': 'Some College',
      'favAnimal': 'ant',
      'favFood': 'duck',
      'charity': 'Partnership to End Addiction',
    },
    {
      'id': 6,
      'pic': require('../../../assets/DummyData/m4.jpg'),
      'firstName': 'Mike',
      'lastName': 'T',
      'city': 'Jacksonville',
      'gender': 'Male',
      'age': 21,
      'maritalStatus': 'Partnered',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'performed on stage, feeling alive under the spotlight.',
      'votes': 68,
      'LEN': 54,
      'state': 'FL',
      'country': 'USA',
      'birthday': '12/25/00',
      'education': 'Some College',
      'favAnimal': 'dog',
      'favFood': 'ribs',
      'charity': 'American Lung Association',
    },
    {
      'id': 7,
      'pic': require('../../../assets/DummyData/m5.jpg'),
      'firstName': 'Christopher',
      'lastName': 'J',
      'city': 'Charlotte',
      'gender': 'Male',
      'age': 43,
      'maritalStatus': 'Single',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'learned Spanish, now able to converse with new friends.',
      'votes': 847,
      'LEN': 55,
      'state': 'NC',
      'country': 'USA',
      'birthday': '5/25/79',
      'education': 'Some College',
      'favAnimal': 'cat',
      'favFood': 'fish tacos',
      'charity': 'Best Friends Animal Society',
    },
    {
      'id': 8,
      'pic': require('../../../assets/DummyData/m6.jpg'),
      'firstName': 'Matthew',
      'lastName': 'M',
      'city': 'Denver',
      'gender': 'Male',
      'age': 27,
      'maritalStatus': 'Single',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'reunited with my long-lost friend, sharing stories over coffee.',
      'votes': 325,
      'LEN': 63,
      'state': 'CO',
      'country': 'USA',
      'birthday': '2/10/95',
      'education': 'Some College',
      'favAnimal': 'fish',
      'favFood': 'chili dogs',
      'charity': 'National UrbanLeaugue',
    },
    {
      'id': 9,
      'pic': require('../../../assets/DummyData/m7.jpg'),
      'firstName': 'Joshua',
      'lastName': 'B',
      'city': 'San Francisco',
      'gender': 'Male',
      'age': 33,
      'maritalStatus': 'Partnered',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': "volunteered for the homeless shelter, making a difference in someone's life.",
      'votes': 512,
      'LEN': 76,
      'state': 'CA',
      'country': 'USA',
      'birthday': '10/15/88',
      'education': 'Some College',
      'favAnimal': 'artic wolf',
      'favFood': 'avacado',
      'charity': 'Partnership to End Addiction',
    },
    {
      'id': 10,
      'pic': '',
      'firstName': 'Alex',
      'lastName': 'T',
      'city': 'Grand Rapids',
      'gender': 'Non-binary',
      'age': 16,
      'maritalStatus': 'Single',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'went on an unplanned road trip, full of laughter and memories.',
      'votes': 370,
      'LEN': 62,
      'state': 'MI',
      'country': 'USA',
      'birthday': '9/24/05',
      'education': 'Some College',
      'favAnimal': 'bullfrog',
      'favFood': 'empanada',
      'charity': 'The Hungar Project',
    },
    {
      'id': 11,
      'pic': require('../../../assets/DummyData/m8.jpg'),
      'firstName': 'Andrew',
      'lastName': 'C',
      'city': 'Tucson',
      'gender': 'Male',
      'age': 19,
      'maritalStatus': 'Single',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'attended a life-changing seminar, finding a new purpose in life.',
      'votes': 365,
      'LEN': 64,
      'state': 'AZ',
      'country': 'USA',
      'birthday': '8/17/03',
      'education': 'High School Graduate',
      'favAnimal': 'shark',
      'favFood': 'cake',
      'charity': 'American Lung Association',
    },
    {
      'id': 12,
      'pic': '',
      'firstName': 'Daniel',
      'lastName': 'R',
      'city': 'Sacramento',
      'gender': '--',
      'age': 36,
      'maritalStatus': 'Divorcedd',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'received unexpected good news, feeling grateful and relieved.',
      'votes': 132,
      'LEN': 61,
      'state': 'CA',
      'country': 'USA',
      'birthday': '10/4/85',
      'education': 'High School Graduate',
      'favAnimal': 'eagle',
      'favFood': 'shrimp',
      'charity': 'Best Friends Animal Society',
    },
    {
      'id': 13,
      'pic': require('../../../assets/DummyData/m9.jpg'),
      'firstName': 'Joseph',
      'lastName': 'L',
      'city': 'Atlanta',
      'gender': 'Male',
      'age': 50,
      'maritalStatus': 'prefer not to answer',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'explored a new city, discovering hidden gems along the way.',
      'votes': 200,
      'LEN': 59,
      'state': 'GA',
      'country': 'USA',
      'birthday': '4/1/72',
      'education': 'PhD',
      'favAnimal': 'flamingo',
      'favFood': 'doritos',
      'charity': 'National UrbanLeaugue',
    },
    {
      'id': 14,
      'pic': require('../../../assets/DummyData/m10.jpg'),
      'firstName': 'Brandon',
      'lastName': 'A',
      'city': 'Omaha',
      'gender': 'Male',
      'age': 35,
      'maritalStatus': 'Partnered',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': ' favorite sports team won the championship, cheering with fellow fans.',
      'votes': 360,
      'LEN': 70,
      'state': 'NE',
      'country': 'USA',
      'birthday': '9/6/87',
      'education': 'High School Graduate',
      'favAnimal': 'baboon',
      'favFood': 'hamburger',
      'charity': 'Partnership to End Addiction',
    },
    {
      'id': 15,
      'pic': require('../../../assets/DummyData/m11.jpg'),
      'firstName': 'David',
      'lastName': 'J',
      'city': 'Oakland',
      'gender': 'Male',
      'age': 26,
      'maritalStatus': 'Married',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'had a deep conversation, feeling understood and heard.',
      'votes': 552,
      'LEN': 54,
      'state': 'CA',
      'country': 'USA',
      'birthday': '2/22/96',
      'education': 'College Graduate',
      'favAnimal': 'hummingbird',
      'favFood': 'chocolate chip cookies',
      'charity': 'The Hungar Project',
    },
    {
      'id': 16,
      'pic': require('../../../assets/DummyData/m12.jpg'),
      'firstName': 'James',
      'lastName': 'G',
      'city': 'Miami',
      'gender': 'Male',
      'age': 17,
      'maritalStatus': 'Single',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'tried a new adventure, exhilarating and unforgettable.',
      'votes': 547,
      'LEN': 54,
      'state': 'FL',
      'country': 'USA',
      'birthday': '2/22/05',
      'education': 'Some High School',
      'favAnimal': 'fox',
      'favFood': 'lychees',
      'charity': 'American Lung Association',
    },
    {
      'id': 17,
      'pic': require('../../../assets/DummyData/f1.jpg'),
      'firstName': 'Amy',
      'lastName': 'R',
      'city': 'Rapid City',
      'gender': 'Female',
      'age': 35,
      'maritalStatus': 'Divorcedd',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'completed a challenging hike, proud of my physical endurance.',
      'votes': 825,
      'LEN': 61,
      'state': 'IA',
      'country': 'USA',
      'birthday': '3/17/89',
      'education': 'Masters Degree',
      'favAnimal': 'caterpillar',
      'favFood': 'peanut butter and jelly',
      'charity': 'Best Friends Animal Society',
    },
    {
      'id': 18,
      'pic': '',
      'firstName': 'Ashley',
      'lastName': 'C',
      'city': 'Cleveland',
      'gender': 'Prefer not to answer',
      'age': 29,
      'maritalStatus': 'Divorcedd',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'attended a music festival, dancing to my favorite songs.',
      'votes': 455,
      'LEN': 56,
      'state': 'OH',
      'country': 'USA',
      'birthday': '2/16/93',
      'education': 'College Graduate',
      'favAnimal': 'chinchilla',
      'favFood': 'pierogies',
      'charity': 'National UrbanLeaugue',
    },
    {
      'id': 19,
      'pic': require('../../../assets/DummyData/f2.jpg'),
      'firstName': 'Cedric',
      'lastName': 'N',
      'city': 'Cincinnati',
      'gender': 'Female',
      'age': 26,
      'maritalStatus': 'Single',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'got a job promotion, feeling recognized and appreciated.',
      'votes': 454,
      'LEN': 56,
      'state': 'OH',
      'country': 'USA',
      'birthday': '6/2/96',
      'education': 'High School Graduate',
      'favAnimal': 'barn owl',
      'favFood': 'french fries',
      'charity': 'Partnership to End Addiction',
    },
    {
      'id': 20,
      'pic': require('../../../assets/DummyData/f3.jpg'),
      'firstName': 'Brittany',
      'lastName': 'C',
      'city': 'St. Louis',
      'gender': 'Female',
      'age': 19,
      'maritalStatus': 'Married',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'finished writing my novel, proud of my hard work and creativity.',
      'votes': 326,
      'LEN': 64,
      'state': 'MS',
      'country': 'USA',
      'birthday': '4/22/03',
      'education': 'Some High School',
      'favAnimal': 'donkey',
      'favFood': 'hot dogs',
      'charity': 'The Hungar Project',
    },
    {
      'id': 21,
      'pic': require('../../../assets/DummyData/f4.jpg'),
      'firstName': 'Sam',
      'lastName': 'P',
      'city': 'Anchorage',
      'gender': 'Female',
      'age': 29,
      'maritalStatus': 'Married',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'went bungee jumping, feeling the rush of adrenaline.',
      'votes': 837,
      'LEN': 52,
      'state': 'AK',
      'country': 'USA',
      'birthday': '4/16/93',
      'education': 'Masters Degree',
      'favAnimal': 'border collie',
      'favFood': 'brownies',
      'charity': 'American Lung Association',
    },
    {
      'id': 22,
      'pic': require('../../../assets/DummyData/f5.jpg'),
      'firstName': 'Sarah',
      'lastName': 'E',
      'city': 'Newport',
      'gender': 'Female',
      'age': 29,
      'maritalStatus': '--',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': "had a picnic with my family, enjoying each other's company.",
      'votes': 31,
      'LEN': 59,
      'state': 'ME',
      'country': 'USA',
      'birthday': '10/21/92',
      'education': 'High School Graduate',
      'favAnimal': 'fly',
      'favFood': 'tacos',
      'charity': 'Best Friends Animal Society',
    },
    {
      'id': 23,
      'pic': require('../../../assets/DummyData/f6.jpg'),
      'firstName': 'Jenifer',
      'lastName': 'T',
      'city': 'Richmond',
      'gender': 'Female',
      'age': 31,
      'maritalStatus': 'Single',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'watched the sunset on the beach, feeling peaceful and content.',
      'votes': 300,
      'LEN': 62,
      'state': 'VA',
      'country': 'USA',
      'birthday': '11/1/90',
      'education': 'Some College',
      'favAnimal': 'squirrel',
      'favFood': 'bagels',
      'charity': 'National UrbanLeaugue',
    },
    {
      'id': 24,
      'pic': '',
      'firstName': 'Lauren',
      'lastName': 'C',
      'city': 'Raleigh',
      'gender': '--',
      'age': 26,
      'maritalStatus': 'Single',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'attended a TED talk, gaining new insights and inspiration.',
      'votes': 76,
      'LEN': 58,
      'state': 'NC',
      'country': 'USA',
      'birthday': '12/9/95',
      'education': 'Some College',
      'favAnimal': 'chipmunk',
      'favFood': 'scallops',
      'charity': 'Partnership to End Addiction',
    },
    {
      'id': 25,
      'pic': '',
      'firstName': 'Liz',
      'lastName': 'P',
      'city': 'Reno',
      'gender': 'Transgender',
      'age': 34,
      'maritalStatus': 'Widowed',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'went to a museum, learning about history and culture.',
      'votes': 705,
      'LEN': 53,
      'state': 'NV',
      'country': 'USA',
      'birthday': '11/10/87',
      'education': 'Some College',
      'favAnimal': 'penguin',
      'favFood': 'chicken nuggets',
      'charity': 'The Hungar Project',
    },
    {
      'id': 26,
      'pic': require('../../../assets/DummyData/f7.jpg'),
      'firstName': 'Emily',
      'lastName': 'C',
      'city': 'Portland',
      'gender': 'Female',
      'age': 21,
      'maritalStatus': 'Single',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'participated in a charity run, supporting a great cause.',
      'votes': 495,
      'LEN': 56,
      'state': 'OR',
      'country': 'USA',
      'birthday': '6/18/01',
      'education': 'College Graduate',
      'favAnimal': 'french bulldog',
      'favFood': 'figs',
      'charity': 'American Lung Association',
    },
    {
      'id': 27,
      'pic': require('../../../assets/DummyData/f8.jpg'),
      'firstName': 'Nicole',
      'lastName': 'N',
      'city': 'Madison',
      'gender': 'Female',
      'age': 22,
      'maritalStatus': 'Partnered',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'went skydiving, feeling like I could conquer the world.',
      'votes': 139,
      'LEN': 55,
      'state': 'WI',
      'country': 'USA',
      'birthday': '5/14/00',
      'education': 'Some College',
      'favAnimal': 'lizard',
      'favFood': 'bok choy',
      'charity': 'Best Friends Animal Society',
    },
    {
      'id': 28,
      'pic': '',
      'firstName': 'Kayla',
      'lastName': 'E',
      'city': 'Topeka',
      'gender': '--',
      'age': 31,
      'maritalStatus': 'Single',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'went to a comedy show, laughing until my stomach hurt.',
      'votes': 6,
      'LEN': 54,
      'state': 'KS',
      'country': 'USA',
      'birthday': '11/25/90',
      'education': 'College Graduate',
      'favAnimal': 'camel',
      'favFood': 'apple pie',
      'charity': 'National UrbanLeaugue',
    },
    {
      'id': 29,
      'pic': require('../../../assets/DummyData/f9.jpg'),
      'firstName': 'Megan',
      'lastName': 'C',
      'city': 'Buffalo',
      'gender': 'Female',
      'age': 35,
      'maritalStatus': 'prefer not to answer',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'received a thoughtful gift from a loved one, feeling loved and appreciated.',
      'votes': 320,
      'LEN': 75,
      'state': 'NY',
      'country': 'USA',
      'birthday': '6/13/87',
      'education': 'Some College',
      'favAnimal': 'barracuda',
      'favFood': 'fast food',
      'charity': 'Partnership to End Addiction',
    },
    {
      'id': 30,
      'pic': require('../../../assets/DummyData/f10.jpg'),
      'firstName': 'Tiffany',
      'lastName': 'G',
      'city': 'Irvine',
      'gender': 'Female',
      'age': 23,
      'maritalStatus': 'Partnered',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'went on a hot air balloon ride, experiencing breathtaking views.',
      'votes': 865,
      'LEN': 64,
      'state': 'CA',
      'country': 'USA',
      'birthday': '8/27/99',
      'education': 'Some College',
      'favAnimal': 'leopard',
      'favFood': 'chicken wrap',
      'charity': 'The Hungar Project',
    },
    {
      'id': 31,
      'pic': require('../../../assets/DummyData/f11.jpg'),
      'firstName': 'Heather',
      'lastName': 'M',
      'city': 'Boise',
      'gender': 'Female',
      'age': 23,
      'maritalStatus': 'Single',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'saw my favorite band live, singing along with the crowd.',
      'votes': 82,
      'LEN': 56,
      'state': 'ID',
      'country': 'USA',
      'birthday': '9/11/99',
      'education': 'College Graduate',
      'favAnimal': 'butterfly',
      'favFood': 'lobster roll',
      'charity': 'American Lung Association',
    },
    {
      'id': 32,
      'pic': require('../../../assets/DummyData/f12.jpg'),
      'firstName': 'Jasmine',
      'lastName': 'K',
      'city': 'Birmingham',
      'gender': 'Female',
      'age': 19,
      'maritalStatus': '--',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'volunteered at an animal shelter, giving love to furry friends.',
      'votes': 422,
      'LEN': 63,
      'state': 'AL',
      'country': 'USA',
      'birthday': '8/6/03',
      'education': 'Some College',
      'favAnimal': 'beagle',
      'favFood': 'bbq chicken',
      'charity': 'Best Friends Animal Society',
    },
    {
      'id': 33,
      'pic': require('../../../assets/DummyData/f13.jpg'),
      'firstName': 'Chris',
      'lastName': 'B',
      'city': 'Huntsville',
      'gender': 'Female',
      'age': 25,
      'maritalStatus': 'Single',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'went to a Broadway show, being swept away by the performance.',
      'votes': 631,
      'LEN': 61,
      'state': 'AL',
      'country': 'USA',
      'birthday': '4/26/97',
      'education': 'College Graduate',
      'favAnimal': 'antelope',
      'favFood': 'rice',
      'charity': 'National UrbanLeaugue',
    },
    {
      'id': 34,
      'pic': require('../../../assets/DummyData/f14.jpg'),
      'firstName': 'Virginia',
      'lastName': 'R',
      'city': 'Santa Fe',
      'gender': 'Female',
      'age': 34,
      'maritalStatus': 'Single',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'had a spa day, pampering myself and feeling rejuvenated.',
      'votes': 247,
      'LEN': 56,
      'state': 'NM',
      'country': 'USA',
      'birthday': '10/12/87',
      'education': 'Masters Degree',
      'favAnimal': 'honey bee',
      'favFood': 'potato salad',
      'charity': 'Partnership to End Addiction',
    },
    {
      'id': 35,
      'pic': '',
      'firstName': 'Joey',
      'lastName': 'W',
      'city': 'Stanton',
      'gender': 'Non-binary',
      'age': 52,
      'maritalStatus': 'Partnered',
      'question': 'One of my favorite days of my life was the day I...',
      'answer': 'went on a camping trip, disconnecting from technology and reconnecting with nature.',
      'votes': 486,
      'LEN': 83,
      'state': 'MI',
      'country': 'USA',
      'birthday': '8/15/70',
      'education': 'Some College',
      'favAnimal': 'panda',
      'favFood': 'eggs',
      'charity': 'The Hungar Project',
    },
   ],
};
export default TodaysLeaders;
